export const SETTING_ICONS = {
  user: '/images/setting/icon-user-cog.svg',
  danger: '/images/setting/icon-triangle-alert.svg',
  confirm: '/images/setting/icon-circle-alert.svg',
  logout: '/images/setting/icon-log-out.svg',
  trash: '/images/setting/icon-trash.svg',
  mail: '/images/setting/icon-mail.svg',
  info: '/images/setting/icon-info.svg',
  package: '/images/setting/icon-package.svg',
  cw: '/images/setting/icon-refresh-cw.svg',
  calendar: '/images/setting/icon-calendar.svg',
  headphones: '/images/setting/icon-headphones.svg',
  help: '/images/setting/icon-circle-help.svg',
  chevron: '/images/setting/icon-chevron-right.svg',
  message: '/images/setting/icon-message-square-text.svg',
  mailBtn1: '/images/setting/icon-mail-btn1.svg',
  mailBtn2: '/images/setting/icon-mail-btn2.svg',
  bugBtn1: '/images/setting/icon-bug-btn1.svg',
  bugBtn2: '/images/setting/icon-bug-btn2.svg',
  messageBtn1: '/images/setting/icon-message-square-text-btn1.svg',
  messageBtn2: '/images/setting/icon-message-square-text-btn2.svg',
  mailFaq: '/images/setting/icon-mail-faq.svg',
  send: '/images/setting/icon-send-horizontal.svg',
}
